제품 상세페이지 (ProductDetailView) 작성
wecode-bootcamp-korea/19-1st-the_meat-backend pull request #16
Opened 2021-04-19 10:22 UTC by Johnywhisky

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
Product app의 ProductDetailView 구현
		 
## 수정 사항들 자세한 내용
제품 상세페이지를 불러오는 api 구현

## 기타 질문 및 특이 사항
postman test 결과
<img width="960" alt="Screen Shot 2021-04-19 at 7 17 14 PM" src="https://user-images.githubusercontent.com/74827666/115221334-8370fc00-a144-11eb-952d-06e7592e362f.png">
프론트엔드와 통신 완료

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-20 13:08 UTC, jamessoun93 requested changes

2021-04-20 13:08 UTC, jamessoun93 commented on products/urls.py
> +    path('/detail/<int:id>', ProductDetailView.as_view()),
`product/<int:id>` 만해도 충분히 RESTful 할 것 같은데 `detail` 이라는 단어가 필요할까요?

2021-04-20 13:08 UTC, jamessoun93 commented on products/views.py
> +from .models import Product
아래 한줄 띄워서 구분해주세요~

2021-04-20 13:08 UTC, jamessoun93 commented on products/views.py
> +    pass
이건뭔가요~?

2021-04-20 13:08 UTC, jamessoun93 commented on products/views.py
> +            product = Product.objects.get(id = id)
`objects.get` 메소드를 활용할 때 잡아주셔야하는 exception 이 있으니 꼭 잡아주세요!

2021-04-20 13:23 UTC, Johnywhisky commented on products/urls.py
> +    path('/detail/<int:id>', ProductDetailView.as_view()),
오호... 그렇네요

2021-04-20 13:25 UTC, Johnywhisky commented on products/views.py
> +    pass
아하 이거 pr날릴 때 기존 클래스 남겨놔야 컨플릭트 최소화 할 수 있을거 같아서 남겨놨었는데 클래스 안에 뭐라도 써야 에러가 안나서 pass만 써놨었어요

2021-04-20 13:26 UTC, Johnywhisky commented on products/views.py
> +            product = Product.objects.get(id = id)
Except도 빼놓다니 개판이네요 ☹

2021-04-21 01:27 UTC, jamessoun93 commented on products/views.py
> +            product = Product.objects.get(id = id)
🐶

2021-04-21 06:20 UTC, Johnywhisky commented
성은이 망극하옵니다

2021-04-22 01:21 UTC, jamessoun93 requested changes

2021-04-22 01:21 UTC, jamessoun93 commented on products/views.py
> +        return JsonResponse({'result': result}, status=200)
리스트뷰는 지원님이 구현하신걸로 아는데 여기 왜 함께 올라와 있을까요?

2021-04-22 01:23 UTC, Johnywhisky commented on products/views.py
> +        return JsonResponse({'result': result}, status=200)
머지하는 과정에서 무슨 짓을 한걸까요...? 흐음...

2021-04-22 01:45 UTC, Johnywhisky commented on products/views.py
> +        return JsonResponse({'result': result}, status=200)
아하 승현님 지원님꺼 매인에 머지되서 제 작업 브랜치에 머지하면서 붙은거같아요

2021-04-22 04:40 UTC, jamessoun93 commented on products/views.py
> +        return JsonResponse({'result': result}, status=200)
음 메인에 머지가 되었으면 새로운 코드로 올라왔으면 안되는건데 이따 같이 보시죠

2021-04-22 04:41 UTC, jamessoun93 requested changes

2021-04-22 04:41 UTC, jamessoun93 commented on .gitignore
> +>>>>>>> main
확인해주세요

2021-04-22 04:41 UTC, jamessoun93 commented on products/views.py
> +        return JsonResponse({'result': result}, status=200)
아 다시 확인해보니 없어졌네요.

2021-04-22 08:57 UTC, jamessoun93 commented
LGTM

2021-04-22 08:57 UTC, merged