Add: product filter 생성
wecode-bootcamp-korea/19-1st-the_meat-backend pull request #17
Opened 2021-04-20 01:20 UTC by jeewonn

## 수정 사항 간략한 한줄 요약
Product filter 생성
		 
## 수정 사항들 자세한 내용
- category, sub_category
- 할인율, 신상품

## 기타 질문 및 특이 사항 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-20 13:03 UTC, jamessoun93 requested changes

2021-04-20 13:03 UTC, jamessoun93 commented on .gitignore
> +>>>>>>> main
흠.. 😩

2021-04-21 00:01 UTC, jeewonn commented on .gitignore
> +>>>>>>> main
흑.....ㅠ

2021-04-21 01:16 UTC, jamessoun93 approved these changes
LGTM

2021-04-21 01:16 UTC, merged