Feature/cart view
wecode-bootcamp-korea/19-1st-the_meat-backend pull request #9
Opened 2021-04-16 12:59 UTC by Johnywhisky

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
For orders App
* urls 수정
* views 직성
		 
## 수정 사항들 자세한 내용
For orders App
* urls 수정. restful API에 맞게
* views 직성. get method요청 시 장바구니 page에 띄울 데이터 전송

## 기타 질문 및 특이 사항
.gitignore에 mysettings.py를 추가해놨는데도 푸쉬 할 때 전송이됩니다... 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-16 12:59 UTC, Johnywhisky commented
mysettings.py 안올라가게 하는 방법 찾아볼게요... 하아........ㄴ.ㅇㄹㅁ.ㄴㄷㄱㄹ ㅏㅣ;ㅓㄴ어라ㅣ;ㄷㄴㅇㄹㅁㄴㄷㄹㅎㄴㄹ휴ㅗㅁㄹㄴㅎ

2021-04-19 07:21 UTC, Johnywhisky commented
이게 뭐지...

2021-04-20 07:26 UTC, jamessoun93 requested changes

2021-04-20 07:26 UTC, jamessoun93 commented on orders/views.py
> +            user_order = Order.objects.filter(Q(user_id = user_id) & Q(status_id = 1)).first()
`get_or_create` 로 변경해보세요!

2021-04-20 07:26 UTC, jamessoun93 commented on orders/views.py
> +                                             Q(status_id = 1)).first())
💚

2021-04-20 13:01 UTC, jamessoun93 commented
@Johnywhisky 서준님 이거 아직일까요?!

2021-04-20 13:04 UTC, Johnywhisky commented
네 지금 update or create적용해보려고 하다가 시간 다날라갔슴다 ㅜㅜㅋㅋㅋㅋㅋㅋ쿠쿠큐큐ㅠㅠㅠ

2021-04-22 01:22 UTC, jamessoun93 requested changes
numbers 파일들 또 올라왔네요. 확인해주세요.

2021-04-22 01:54 UTC, Johnywhisky commented
넘버스 삭제했습니다

2021-04-22 04:40 UTC, merged